### ISSUE TITLE
Conda install issue. Blank Errors.

### ISSUE THREAD

**Issue by kiahalespractice** [higlass/higlass#1074]
Conda higlass has a hidden/uncommunicated bioconda dependency. Please update your documentation.

#### Steps to reproduce
`conda install -c jrhawley higlass-python`

or

`conda create -n higlass -c jrhawley higlass-python`

#### Observed behavior
```Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: | 
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed 

UnsatisfiableError: The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versions
```

Note that it does not say there is a missing bioconda dependency.

#### Solution
`conda create -n higlass -c jrhawley -c conda-forge -c bioconda higlass-python`

**Comment by nvictus** [comment]
AFAIK, we do not currently maintain an official conda package. This seems to be a recipe from @jrhawley's personal conda channel.

**Comment by jrhawley** [comment]
Hi @kiahalespractice, @nvictus is right, this is a conda recipe from my personal use.
It's not listed on bioconda or supported by the higlass developers.

To make this work you would need to either:
1. add my personal conda channel to your `~/.condarc` file, or
2. manually specify the package's dependencies that I have also made conda packages for in my personal channel.

You can add my personal channel by adding this to your `~/.condarc` file:

```yaml
channels:
  - jrhawley
  - bioconda
  - conda-forge
```

Or you can manually specify the dependencies in the command line like so:

```shell
conda install -c jrhawley higlass-python clodius negspy pybbi simple-httpfs slugid
```

Again, all of those are my own personal conda recipes that I made.
It's a bit experimental because they're not currently supported by the developers of those packages or listed in bioconda.
You may run into some dependency troubles.
You can contact me directly, though, if you want some help with that.

Since this isn't an issue for the developers, I think you can probably close the issue.

**Comment by nvictus** [comment]
Thanks for the details, @jrhawley!

I'm glad you got conda recipes working. I'd be curious to see your `pybbi` recipe. I do release multiple platform wheels for it, but it took quite a bit of effort to avoid introducing linking errors when compiling the UCSC library.

**Comment by kiahalespractice** [comment]
Thank you for your guys' help! My bad for overlooking authorship.
