### ISSUE TITLE
Remove config links from google search results

### ISSUE THREAD

**Issue by pkerpedjiev** [higlass/higlass#164]
These results should not appear in Google's search results:

![image](https://user-images.githubusercontent.com/2143629/32006008-ab247626-b973-11e7-9094-fb029a2815d9.png)

**Comment by mccalluc** [comment]
It might be because better links have risen to the top, rather than explicitly preventing indexing, but this doesn't seem to be a problem any longer, at least in the first couple result pages. Closing.

![Screen Shot 2019-06-04 at 5 09 51 PM](https://user-images.githubusercontent.com/730388/58914232-fbb6ab80-86eb-11e9-859d-68b829dd4555.png)
