### ISSUE TITLE
Current higlass.io website is confusing/deceiving with genome versions

### ISSUE THREAD

**Issue by mimakaev** [higlass/higlass#339]
Currently, if you switch the selector from hg19 to hg38, nothing happens. The website says "hg38", but displayed data is still hg19. It may cause confusion among users. 

Also, some data on highlass.io is mapped to hg19, and some to hg38, and the website does not say what is what.  

Steps to reproduce: 

-- Open higlass.io
-- Find selector "hg19", click it, select "hg38".

**Comment by pkerpedjiev** [comment]
To be fair, something *does* happen. The coordinates in the search bar change.

![oct-28-2018 17-58-02](https://user-images.githubusercontent.com/2143629/47622400-0f0cf300-dadb-11e8-9d7c-8e4bb988cbb5.gif)

But you're right, it is confusing. Starting in the next release, we'll require people to include a coordSystem (i.e. assembly) with any bigWig or cooler file.  Most of the datasets on http://higlass.io actually store that information internally but it's not apparent when listing the datasets. It *is* however, visible once the dataset is added:

![image](https://user-images.githubusercontent.com/2143629/47622489-c3a71480-dadb-11e8-9be2-762f33eafb2c.png)

This issue has highlights a long standing and unresolved pain point. We don't want to enforce a particular assembly because it should be possible to add compatible variations (e.g. `hg19` and `b37`) to the same view. But this can be difficult to ascertain.

At the very list we need to be more verbose when there are conflicts between e.g. the search bar and the visible datasets.

If you have any other ideas for how we can make this more clear and/or easier to use, they would be greatly appreciated.

**Comment by mccalluc** [comment]
Since some progress was made with that release...
> Starting in the next release, we'll require people to include a coordSystem (i.e. assembly) with any bigWig or cooler file.

I'll go ahead and close this, but please reopen if there is still a problem, and we can articulate what the next steps should be.
