### ISSUE TITLE
How does higlass deal with unevenly sized bins at the end of chromosomes?

### ISSUE THREAD

**Issue by liz-is** [higlass/higlass#425]
_Commit_: 

#### Steps to reproduce
1. Go to higlass.io and load a dataset, e.g. [hicnorm] Rao et al. (2014) GM12878 MboI Primary
2. Add the 2D chromosome grid and horizontal chromosome labels for the corresponding genome version
3. Set zoom limit to 100kb (or another low resolution)
4. Zoom in to the end of one chromosome / start of another (e.g. end of chr3 / start of chr4)
N.B. this isn't apparent in all datasets as the ends of chromosomes are very often unmappable.  

#### Observed behavior
- The chromosome grid line crosses in the middle of a bin, not at the edge of a bin. 
- All displayed bins are the same width.

![screen shot 2018-11-22 at 12 26 59](https://user-images.githubusercontent.com/3035709/48900176-f7aef480-ee51-11e8-801a-aef6e507f47e.png)

#### Expected behavior
- A smaller bin is displayed at the end of a chromosome, to account for the chromosome length not being an exact multiple of 100kb (or 5kb, 2kb, etc...) - either with data if available, or with the NA value. 
- Chromosome grid lines line up with the boundaries between bins.

I noticed this behaviour when I was working with a cooler file at low resolution for testing purposes. It looks like the final bins, which are less than the "base" bin size, e.g. 100kb, are not being displayed at all. I'm concerned that this could lead to the Hi-C matrix data being out of sync with other annotations.

**Comment by pkerpedjiev** [comment]
That's a good question! We've had a number of internal discussions about this very topic. The solution we adopted is imperfect yet functional: we display a grid of points where the value of each point is the value of the bin closest to its end.

So imagine if we have cooler bins of length 4. The the arrangement of bins along the genome would look like this: 

```
chroms: 11111112222222222
bins:   11112233334444555
```

If we want to display this in higlass with a grid size of three, the grid will look like this:

```
grid:       aaabbbcccdddeeefff
```

So the interpolated bins will look like the second line below:

```
chroms: 11111112222222222
bins:   11112233334444555
grid:   aaabbbcccdddeeefff
data:   111222333444555NNN
```

Notice that the first bin actually takes up less space than it should, the second takes up more, the third less, the fourth less and the fifth is the same. The `N`'s at the end are NaN values because there's no value at the end of the grid.

So to address your concern, the annotations should never be systematically shifted with respect to the matrices. Although due to the limitations in how we retrieve and display the matrix data, it will always be slightly distorted. Ideally, in most cases, the pixels will be small enough that it's not noticeable. When using large bins or zooming in far enough, you do end up seeing the artifacts that you noticed.

Does that make sense? In case you're curious, this is where all this happens: https://github.com/higlass/hgtiles/blob/74ef477b9df953edef7b67a0153fc98490572f9b/hgtiles/cooler.py#L328

**Comment by liz-is** [comment]
Should that be

```
chroms: 11111122222222222
bins:   11112233334444555
```
? Otherwise bin 3 spans the two chromosomes...

Otherwise, yes, I think that makes sense! It's good to know that there are not any distortions in the data, rather it's just an artefact of how it's displayed. Thanks for the explanation!

**Comment by pkerpedjiev** [comment]
Yes, you're right. My mistake.
