### ISSUE TITLE
View header icons in Safari are off

### ISSUE THREAD

**Issue by flekschas** [higlass/higlass#569]
_Commit_: higlass.io

#### Steps to reproduce
1. Open higlass.io in Safari

#### Observed behavior
- Those view header icons are way to high!

![screen shot 2019-02-20 at 4 52 52 pm](https://user-images.githubusercontent.com/932103/53127230-fc0dab00-352f-11e9-890b-6d97c92c42fc.png)

#### Expected behavior
- The height of the icons should be normal.

**Comment by ngehlenborg** [comment]
This problem is back.

_Commit_: Whatever is running on https://higlass.io/app today.

#### Steps to reproduce
 1. Open https://higlass.io/app in Safari Version 12.1.1 (14607.2.6.1.1) on Mac OS X 10.14.5 (18F132)
 1. Look at copy/settings/etc. controls for the main view.

#### Observed behavior
- Controls for view are not shown where they belong.

<img width="216" alt="image" src="https://user-images.githubusercontent.com/1216518/60822156-bc9bd000-a159-11e9-90a0-c30bb0e8a69f.png">

#### Expected behavior
- Controls are where they belong.

**Comment by ngehlenborg** [comment]
A hard reload fixed the issue for now.
