### ISSUE TITLE
Quick question

### ISSUE THREAD

**Issue by tarak77** [higlass/higlass#665]
Hi,

In the HiC maps produced/visualized, I have been asked by others regarding the white lines we see in these maps chromosome wide. I have no idea what they mean but any help from you would be great?

Thanks!

**Comment by nvictus** [comment]
Greyed out horizontal and vertical bands in the heatmap represent genomic bins that were filtered or masked during the normalization process due to lack of reference sequence identity (NNN...) or low coverage (e.g. due to poor mappability or low restriction site density). As you can see the widest bands correspond to assembly gaps at centromeres and telomeres. 

Note that you can turn off normalization (Configure Series -> Transforms -> None) to see what the raw counts look like before masking.

**Comment by flekschas** [comment]
Closing this. Please reopen if you have more related questions.
