### ISSUE TITLE
Tooltip doesn't show value (shows NA)

### ISSUE THREAD

**Issue by mimakaev** [higlass/higlass#747]
On github.io as well as on local installation, enabling tooltip does not show the value - it shows "N/A". 
![image](https://user-images.githubusercontent.com/9454715/61903589-d0ce2400-aef2-11e9-8a5f-c60695353842.png)

_Commit_: 

#### Steps to reproduce
1.

#### Observed behavior
- 

#### Expected behavior
-

**Comment by flekschas** [comment]
Locally in `develop` I can't reproduce the issue

**Comment by mimakaev** [comment]
Locally we have v1.6.5 - that's the latest I get from docker - and it shows "NaN" rather than "N/A"

**Comment by flekschas** [comment]
I can reproduce this locally in the docker image too. Even with the very latest version of `hglib` and `hga` that both work individually but in the docker image the tooltip all of a sudden stops working.

**Comment by flekschas** [comment]
Ohhhhh it's working again locally when I use an unminimized version of `hglib`...

**Comment by flekschas** [comment]
Holy lord... somehow this line of code gets lost during minification: https://github.com/higlass/higlass/blob/develop/app/scripts/utils/ndarray-assign.js#L31

Without this line no value is copied from the extracted data into a new ndarray object, which is why we see `N/A` at the end as the ndarray is initialized with `NaN`.

Even weirder when I pad this line of code with two `console.log()` statements the line is preserved! I think somehow the minimizer is messed up.

This is by far the weirdest error I ever encountered

**Comment by flekschas** [comment]
I have no idea why the code ever worked. The minimizer did the correct job and that value was always removed (because it normally would be a meaningless assignment). I figured out a workaround. Now it works locally with a production build as expected.
