### ISSUE TITLE
Saving views / tracks for future browsing

### ISSUE THREAD

**Issue by faryabib** [higlass/higlass#938]
Thanks to your prompt replies, we eventually migrated most of our data to HiGlass. I originally had two questions, the second on of which about uploading non-semantic sorted bedgaph was resolved. 

The remaining question is whether we could save a HiGlass view with its tracks for future browsing. Basically, something like a session in other genome browsers.   

Thanks -- B.

**Comment by faryabib** [comment]
Regarding my earlier post, I managed to generated .hitile file from the bedgraph 

clodius aggregate bedgraph \
--chromosome-col 1 \
--from-pos-col 2 \
--to-pos-col 3 \
--value-col 4 \
--assembly hg19 \
--transform none \
--method sum \
--no-header \
--chromsizes-filename ~/hg-tmp/ChromInfo_chr.txt \
~/hg-tmp/my.bedgraph

What would be an appropriate ingest options?

Thanks -- B.

**Comment by pkerpedjiev** [comment]
Hi, I would recommend converting to bigWig rather than hitile. The bigWig format has much more widespread support and we will deprecate the hitile format in the not too distant future.

For saving your views for later, you can either "Export as link" in which case you can click on the link and it'll take you back to the same view you were using or you can "Export as JSON" which will save the current configuration as a JSON file. You can then drag that JSON file onto the higlass viewer and it will be restored.

<img width="411" alt="image" src="https://user-images.githubusercontent.com/2143629/85903017-350bfe80-b7ba-11ea-9c1e-0b308fa969fa.png">

**Comment by sehilyi** [comment]
I am closing this issue since the question seems to be addressed already, but feel free to re-open this if there is anything left for further discussion.
