### ISSUE TITLE
how to download or access public .cool files included in higlass 

### ISSUE THREAD

**Issue by cityCoder** [higlass/higlass#956]
higlass is a great tool for Hi-C visualizations. I find it comes with many  Hi-C files for easy visualization. I would like to ask are there approaches to download .cool files or read them directly with API.

Best,
Yanlin

**Comment by pkerpedjiev** [comment]
We don't offer the files for download because it has the potential to lead to large data transfer costs. With that said, you can still go on the higlass Slack channel (http://bit.ly/higlass-slack) and ask for the data. Some kind soul may just be willing to send them to you ;-)

What type of API would you like to access them with?

**Comment by nvictus** [comment]
Also worth mentioning that the [4DN data portal](https://data.4dnucleome.org/) has many files available.

**Comment by cityCoder** [comment]
Thank you!
I'll try to seek help on the slack channel. An API support direct access to user-specific regions would be great. Something like we access local .cool files with cooler.

Yes, 4DN data portal is a nice place, I've downloaded all datasets. I realized higlass provides more data than 4DN.

**Comment by Gavin-Lijy** [comment]
slack link doesn't work
